### ISSUE TITLE
Expresso is loading but nothing happens when UI buttons are clicked.

### ISSUE THREAD

**Issue by wwwonka** [fcamarlinghi/expresso#13]
I have been trying to make Expresso 0.6.1 work  on my machine in Photoshop CC 2020 and 2021 without success.

The extension doesn't do anything when I press UI buttons inside the panel (I can access the settings but nothing happens when I press the folder, + and arrow buttons).
This has been the case both while running the extension from a debug build or installing the signed ZXP package downloaded from gumroad.

Running the Expresso scripts in File>Scripts has no effect as well

No error is showing up in the Chromium dev console, I only see this warning:  
`[Settings] [WARN] Error reading settings file, starting clean.`

Generator and remote connections are turned on in PS settings.

Perhaps I am misunderstanding how to set up properly a document for the extension to work.
Do I have to name layers or groups in a certain way like for the asset generator?

I am on macOS Catalina 10.15.7

**Comment by fcamarlinghi** [comment]
Hi, no document setup is required for the extension to work so what you're describing looks like a bug. Can you please share a full log after performing some actions (i.e. adding an export target)? So that I can compare it to what I see on my machine.

**Comment by wwwonka** [comment]
Hi Francesco,
Unfortunately nothing shows up in the `exporter-main.log` file apart from  
`Log file created on Tue Nov 10 2020 20:03:07 GMT-0500 (EST)`  
Pressing any of the UI buttons does nothing there as well I am afraid.


For the `exporter-settings.log` file, some more is showing up at initial load but nothing happens when I try to click there as well. Here is a copy-paste of it anyways:
```
Log file created on Sun Nov 08 2020 03:57:52 GMT-0500 (GMT-05:00)
03:57:52.201 [CEP] [DEBUG] addEventListener: com.expresso.settingsUpdated 
03:57:52.203 [CEP] [DEBUG] addEventListener: com.adobe.csxs.events.ThemeColorChanged 
03:57:52.204 [CEP] [DEBUG] getHostEnvironment 
03:57:52.205 [Settings] [INFO] Loading settings from Library/Application Support/Expresso/Exporter/settings.json 
03:57:52.205 [Settings] [WARN] Error reading settings file, starting clean. 
03:57:52.207 [Extension] [INFO] Extension Expresso Exporter Settings 0.6.1 initialized. 
03:57:54.658 [Settings] [INFO] Saving settings to Library/Application Support/Expresso/Exporter/settings.json 
03:57:54.659 [CEP] [DEBUG] dispatchEvent: com.expresso.settingsUpdated 
03:57:54.659 [CEP] [DEBUG] getHostEnvironment 
03:57:54.660 [CEP] [DEBUG] getExtensionId 
03:57:55.293 [Settings] [INFO] Saving settings to Library/Application Support/Expresso/Exporter/settings.json 
03:57:55.293 [CEP] [DEBUG] dispatchEvent: com.expresso.settingsUpdated 
03:57:55.293 [CEP] [DEBUG] getHostEnvironment 
03:57:55.294 [CEP] [DEBUG] getExtensionId 
```

The extension works just fine on my Windows 10 Boot Camp partition, so this must have something to do with macOS Catalina...

**Comment by wwwonka** [comment]
Some more is showing up when I use the official build from gumroad. Although apart from changing the export folder (i.e. typing a new path in the text bar), pressing on any UI button does not update the log file as well...

[exporter-main.log](https://github.com/fcamarlinghi/expresso/files/5521090/exporter-main.log)

**Comment by fcamarlinghi** [comment]
Thanks for the logs and for taking the time to test it on Windows as well. It indeed seems to be a Mac-specific bug. Since nothing appears on the logs it might be related to event handling, but I'm unsure as to what might be causing it. I'll try to get it fixed over the next few days.

**Comment by fcamarlinghi** [comment]
I tracked the problem down to pointer events not working correctly on Mac for some reasons. I implemented a workaround in a [separate branch](https://github.com/fcamarlinghi/expresso/tree/fix__macos-support), alongside a fix for another issue related to export paths.

Can you please update and confirm that this fixes the problem on your end as well?

**Comment by wwwonka** [comment]
Yes! It does work now.
And very well, may I say sir.

**Comment by fcamarlinghi** [comment]
Great! A new build with these fixes in now [available on Gumroad](https://gum.co/expresso-exporter).
