### ISSUE TITLE
Remote connections issue: Default password has changed

### ISSUE THREAD

**Issue by cschonewill** [fcamarlinghi/expresso#16]
Upon installing the latest version of photoshop, I tried to install Expresso but am hitting an issue. The default password set under enable remote connections is now four characters, and when you attempt to save after enabling these two things it says the password needs to be six characters, meaning in order to save you have to change the default password. I don't know if this is new, but it's a blocker to being able to install and use Expresso! 

Please advise!

![image](https://user-images.githubusercontent.com/44623275/109706656-d542d000-7b5e-11eb-86b6-268895186fc6.png)

**Comment by fcamarlinghi** [comment]
You should be able to get it to work by setting the password to "password" as highlighted in the [installation guide](https://minifloppy.it/tools/expresso/#help-initial-setup).

(Not sure if the default password has always been 4 characters long though, it's been a while since I had to set up a clean install of Photoshop).

**Comment by cschonewill** [comment]
Ah I apologize that I missed the part there where it said the password was password. Apologies, was rushing a bit. 

I have that set now, however I'm having installation issues likely due to recent version compatibility. 

![image](https://user-images.githubusercontent.com/44623275/109829492-345a2080-7c03-11eb-8876-9eabb1b5f976.png)

Just need to wait for a version that's compatible with latest, or is there something else I can do?

**Comment by fcamarlinghi** [comment]
No worries!

Yeah, sorry, should've mentioned that. Unfortunately there's an unresolved bug with ZXP Installer that results in installation failing in some cases with Photoshop 2021. Until a fix is included in the official ZXP Installer distribution I created a version of the plugin that includes a simple standalone installer: https://www.dropbox.com/s/z35jrwvi3x5mmr7/expresso_exporter_0.6.3_installer.zip?dl=1

Simply extract the zip file and run "install.bat" as admin.

**Comment by cschonewill** [comment]
Ah I'm glad I asked, thank you for that - it worked! Cheers Francesco!
