### ISSUE TITLE
Can compile but panel stay blank

### ISSUE THREAD

**Issue by aridercas** [fcamarlinghi/expresso#2]
Hi! I successfully packed the expresso.exporter_0.5.0.ZXP file following all the instructions but when I run both PS 2015 and 2017 the panels remain blank. I enabled Remote Connections in Photoshop preferences too.

Thanks.

**Comment by fcamarlinghi** [comment]
Hi, sorry for the late reply! Have you doubled checked that the password is set to "password" in Photoshop preferences?

**Comment by aridercas** [comment]
Hello, yes, I have set the password as specified in github but the PS
panels were still blank. Anyway no longer necessary, I got the version 0.42
of Expresso and PS 2014 and with that I have already been able to work.
Even so, many thanks for answering and developing such a useful tool, I
have combined it with several actions and it has changed my workflow making
it much more flexible and fast. If someday you decide to create an updated
version would be some fantastic because I would love to keep these
functionalities in my workflow. So if you ever decide and need someone to
test and feedback, would be happy to participate. Best regards. Aitor Rider.

2017-08-09 17:22 GMT+02:00 Francesco Camarlinghi <notifications@github.com>:

**Comment by fcamarlinghi** [comment]
Glad to hear that, and thanks for the kind words about the extension. Unfortunately, spare time to work on it has been hard to find over the last year, so for the moment the extension (as well as related projects such as _cepy_) is in a "minimal life support" mode. But yeah, I hope I'll be able to get back to it sometimes in the future, there are a lot of features I would love to implement!
