### ISSUE TITLE
buttons isn't work

### ISSUE THREAD

**Issue by ghbreel2911** [fcamarlinghi/expresso#28]
hi 
expresso isn't connect to photoshopserver and if connect buttons isn't work
[exporter-main.log](https://github.com/fcamarlinghi/expresso/files/9226056/exporter-main.log)

**Comment by fcamarlinghi** [comment]
Hi! Thanks for the log. I've seen this happen a few times in the past for other users, but unfortunately I was never able to identify a specific cause for this issue. Some things to try / look out for that helped in those cases:

- Reinstalling the plugin fixed the problem in a few cases.
- If you're using a firewall/antivirus try to disable it momentarily to see if it helps.
- If you have other Photoshop plugins installed, try to disable them momentarily. I've seen cases where other plugins were preventing Expresso from working correctly.
- Updating Photoshop to the latest version also helped in some cases. There may be a bug in your specific version preventing the plugin from working.
