### ISSUE TITLE
Any chance for ARM apple silicons version?

### ISSUE THREAD

**Issue by kbielenin** [fcamarlinghi/expresso#34]
Great plugin, would be amazing to have it native on M chips.

**Comment by fcamarlinghi** [comment]
Unfortunately the technology the plugin is built on is being phased out by Adobe and hasn't been updated to support Apple Silicon natively. Until Adobe provides a viable alternative I can use to upgrade the plugin to, you can try to do the following:

![image](https://github.com/fcamarlinghi/expresso/assets/789284/9ff70928-b020-482f-aade-b9e438ced536)

(taken from [here](https://helpx.adobe.com/photoshop/kb/photoshop-for-apple-silicon.html))
