### ISSUE TITLE
i get a error today :(

### ISSUE THREAD

**Issue by genics** [fcamarlinghi/expresso#6]
unable to export"_albedo". undfined is not a function, 

can you help me man?

this is log:
18:41:42.355 [CEP] [DEBUG] evalScript:
 var params = {};var documentPath="";try{if(params.documentId){for(var i=0,l=app.documents.length;i<l;i++){if(app.documents[i].id===params.documentId){documentPath=app.documents[i].fullName.fsName;break;}}}else{documentPath=app.activeDocument.fullName.fsName;}}catch(e){}documentPath; 
18:41:42.358 [Extension] [DEBUG] Export folder is relative to document path E:\IGG\wright brother\model\ (./) 
18:41:42.359 [Photoshop] [DEBUG] _sendScript: var params = {"documentId":null,"flags":{"compInfo":false,"imageInfo":true,"layerInfo":true,"expandSmartObjects":false,"getTextStyles":false,"getFullTextStyles":false,"selectedLayers":false,"getCompLayerSettings":false,"getDefaultLayerFX":false,"getPathData":false}};var idNS=stringIDToTypeID("sendDocumentInfoToNetworkClient"),desc=new ActionDescriptor();desc.putString(stringIDToTypeID("version"),"1.3.0");for(var key in params.flags){if(params.flags.hasOwnProperty(key)){desc.putBoolean(stringIDToTypeID(key),params.flags[key]);}}if(params.documentId){desc.putInteger(stringIDToTypeID("documentID"),params.documentId);}executeAction(idNS,desc,DialogModes.NO); 
18:41:42.400 [Photoshop] [DEBUG] _sendScript: var params = {"documentId":225,"layerSpec":3,"scaleX":1,"scaleY":1,"bounds":true,"boundsOnly":false,"useSmartScaling":false,"includeAncestorMasks":false,"includeAdjustors":false,"convertToWorkingRGBProfile":false,"getICCProfileData":false,"allowDither":false,"useColorSettingsDither":false,"forceSmartPSDPixelScaling":false,"clipToDocumentBounds":true,"maxDimension":16384};var DEFAULT_MAX_DIMENSION=10000,desc=new ActionDescriptor(),transform;if(params.inputRect&&params.outputRect){transform=new ActionDescriptor();var inputRect=params.inputRect,psInputRect=new ActionList();psInputRect.putUnitDouble(charIDToTypeID("#Pxl"),inputRect.left);psInputRect.putUnitDouble(charIDToTypeID("#Pxl"),inputRect.top);psInputRect.putUnitDouble(charIDToTypeID("#Pxl"),inputRect.right);psInputRect.putUnitDouble(charIDToTypeID("#Pxl"),inputRect.bottom);transform.putList(stringIDToTypeID("rectangle"),psInputRect);var outputRect=params.outputRect,psOutputCorners=new ActionList();psOutputCorners.putUnitDouble(charIDToTypeID("#Pxl"),outputRect.left);psOutputCorners.putUnitDouble(charIDToTypeID("#Pxl"),outputRect.top);psOutputCorners.putUnitDouble(charIDToTypeID("#Pxl"),outputRect.right);psOutputCorners.putUnitDouble(charIDToTypeID("#Pxl"),outputRect.top);psOutputCorners.putUnitDouble(charIDToTypeID("#Pxl"),outputRect.right);psOutputCorners.putUnitDouble(charIDToTypeID("#Pxl"),outputRect.bottom);psOutputCorners.putUnitDouble(charIDToTypeID("#Pxl"),outputRect.left);psOutputCorners.putUnitDouble(charIDToTypeID("#Pxl"),outputRect.bottom);transform.putList(stringIDToTypeID("quadrilateral"),psOutputCorners);}else{if(params.scaleX&&params.scaleY&&(params.scaleX!==1||params.scaleY!==1)){transform=new ActionDescriptor();transform.putBoolean(stringIDToTypeID("forceDumbScaling"),!params.useSmartScaling);transform.putDouble(stringIDToTypeID("width"),params.scaleX*100);transform.putDouble(stringIDToTypeID("height"),params.scaleY*100);}}if(transform){transform.putBoolean(stringIDToTypeID("forceDumbScaling"),!params.useSmartScaling);if(params.hasOwnProperty("interpolationType")){transform.putEnumerated(stringIDToTypeID("interpolation"),stringIDToTypeID("interpolationType"),stringIDToTypeID(params.interpolationType));desc.putEnumerated(stringIDToTypeID("interpolation"),stringIDToTypeID("interpolationType"),stringIDToTypeID(params.interpolationType));}transform.putBoolean(stringIDToTypeID("forceSmartPSDPixelScaling"),!!params.forceSmartPSDPixelScaling);desc.putObject(stringIDToTypeID("transform"),stringIDToTypeID("transform"),transform);}desc.putInteger(stringIDToTypeID("documentID"),params.documentId);desc.putInteger(stringIDToTypeID("width"),params.maxDimension||DEFAULT_MAX_DIMENSION);desc.putInteger(stringIDToTypeID("height"),params.maxDimension||DEFAULT_MAX_DIMENSION);desc.putInteger(stringIDToTypeID("format"),2);if(typeof(params.layerSpec)==="object"){desc.putInteger(stringIDToTypeID("firstLayer"),params.layerSpec.firstLayerIndex);desc.putInteger(stringIDToTypeID("lastLayer"),params.layerSpec.lastLayerIndex);if(params.layerSpec.hasOwnProperty("hidden")&&params.layerSpec.hidden.length>0){var i,hiddenIndicesMap={},settingsList=new ActionList(),hiddenLayerDesc=new ActionDescriptor(),visibleLayerDesc=new ActionDescriptor(),hiddenLayerSettings=new ActionDescriptor(),lsID=stringIDToTypeID("layerSettings");hiddenLayerSettings.putBoolean(stringIDToTypeID("enabled"),false);hiddenLayerDesc.putObject(lsID,lsID,hiddenLayerSettings);for(i=0;i<params.layerSpec.hidden.length;i++){hiddenIndicesMap[params.layerSpec.hidden[i]]=true;}for(i=params.layerSpec.firstLayerIndex;i<=params.layerSpec.lastLayerIndex;i++){if(hiddenIndicesMap[i]){settingsList.putObject(lsID,hiddenLayerDesc);}else{settingsList.putObject(lsID,visibleLayerDesc);}}desc.putList(stringIDToTypeID("layerSettings"),settingsList);}}else{desc.putInteger(stringIDToTypeID("layerID"),params.layerSpec);}if(params.hasOwnProperty("compId")){desc.putInteger(stringIDToTypeID("compID"),params.compId);}else{if(params.hasOwnProperty("compIndex")){desc.putInteger(stringIDToTypeID("compIndex"),params.compIndex);}}if(params.includeAncestorMasks){desc.putEnumerated(stringIDToTypeID("includeAncestors"),stringIDToTypeID("includeLayers"),stringIDToTypeID("includeVisible"));}else{desc.putEnumerated(stringIDToTypeID("includeAncestors"),stringIDToTypeID("includeLayers"),stringIDToTypeID("includeNone"));}if(params.includeAdjustors){desc.putEnumerated(stringIDToTypeID("includeAdjustors"),stringIDToTypeID("includeLayers"),stringIDToTypeID("includeVisible"));}else{desc.putEnumerated(stringIDToTypeID("includeAdjustors"),stringIDToTypeID("includeLayers"),stringIDToTypeID("includeNone"));}desc.putBoolean(stringIDToTypeID("convertToWorkingRGBProfile"),!!params.convertToWorkingRGBProfile);if(params.hasOwnProperty("useICCProfile")){desc.putString(stringIDToTypeID("useICCProfile"),params.useICCProfile);}desc.putBoolean(stringIDToTypeID("sendThumbnailProfile"),!!params.getICCProfileData);desc.putBoolean(stringIDToTypeID("allowDither"),!!params.allowDither);desc.putBoolean(stringIDToTypeID("useColorSettingsDither"),!!params.useColorSettingsDither);desc.putBoolean(stringIDToTypeID("clipToDocumentBounds"),!!params.clipToDocumentBounds);desc.putBoolean(stringIDToTypeID("boundsOnly"),!!params.boundsOnly);desc.putBoolean(stringIDToTypeID("bounds"),!!params.bounds);executeAction(stringIDToTypeID("sendLayerThumbnailToNetworkClient"),desc,DialogModes.NO); 
18:41:42.831 [CEP] [DEBUG] getExtensionInfo 
18:41:42.831 [CEP] [DEBUG] evalScript:
 var params = {"text":"Unable to export \"_albedo\". undefined is not a function","title":"Expresso Exporter"};alert(params.text,params.title) 
18:41:42.832 [Extension] [ERROR] Unable to export "_albedo". undefined is not a function

**Comment by genics** [comment]
ok. it is work again when i reinstall photoshop!no problem now.

**Comment by fcamarlinghi** [comment]
Hey, sorry for the delay! Glad you managed to solve the issue. Closing this now, but feel free to reopen it in case you experience the problem again.
