### ISSUE TITLE
Compressed TGA?

### ISSUE THREAD

**Issue by Shadetail** [fcamarlinghi/expresso#9]
Is it somehow possible to export to compressed TGA rather than uncompressed? Because I can't find such option anywhere, and since TGA compression is both lossless and fast, there's little reason not to use it. My studio even plans to start enforcing compression as requirement on all submitted TGA, since once there are thousands of textures in the project, differences between all of them being compressed or not is few hundred gigabytes per workstation.

**Comment by fcamarlinghi** [comment]
Thanks for the suggestion! Support for compressed TGA is available in version 0.6 that's out now. It can be enabled in the settings:

![expresso-tga-compression](https://user-images.githubusercontent.com/789284/79216754-02569900-7e4e-11ea-888a-5acbb506f66a.png)

Please let me know if you run into any issues.

**Comment by Shadetail** [comment]
I just saw the update and tested it and the TGA compression works perfectly!
To extend my thanks, I went and bought your game Guntastic on Steam.
Stay awesome :)

**Comment by fcamarlinghi** [comment]
Glad to hear everything's working fine. Hope you enjoy the game! :)
